<?php

/**
 * @var \OpenPix\Pix\Block\Info\Pix $block
 */

$order = $block->getInfo()->getOrder();
?>

<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <?php if ($order): ?>
            <img src="<?= $order->getOpenpixQrcodeimage() ?>" width="200" height="200" />
        <?php endif; ?>
    </dd>
</dl>