<?php
$paymentInfo = $block->getPaymentInfo();
$src = $block->getPluginSrc();
$correlationID = $block->getCorrelationID();
$appID = $block->getAppID();

if ($block->getPaymentMethod() === 'openpix_pix'): ?>
    <?php if(!$block->isSendEmail()) {?>
        <button type="button" class="action primary btn-openpix-pix" data-trigger="trigger">
            <span data-bind="i18n: '<?= $paymentInfo['text'] ?? '' ?>'"></span>
        </button>
        <div data-bind="mageInit: {
            'Magento_Ui/js/modal/modal':{
                'type': 'popup',
                'modalClass': 'modalpix',
                'title': 'Escaneie o QRcode',
                'trigger': '[data-trigger=trigger]',
                'responsive': true,
            }}">
            <div id="openpix-order" data-appid="<?= $appID ?>" data-correlationID="<?= $correlationID ?>"></div>
            <script>// <![CDATA[
                require(["jquery","OpenPix"],function($,pym){
                });
                // ]]>
            </script>
        </div>
    <?php } else {?>
        <div class='flex-column-center'>
            <img
                    class='openpix-qrcode-image'
                    title='QRCode Pix deste pedido.'
                    src="<?= $paymentInfo['text'] . '?size=600'; ?>"
                    width='200px'
            />
        </div>
        <style>
            .flex-column-center {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
            .openpix-qrcode-image {
                width: 200px !important;
            }
        </style>
    <?php } ?>
<?php endif; ?>
