<?php
$paymentInfo = $block->getPaymentInfo();
$src = $block->getPluginSrc();
$correlationID = $block->getCorrelationID();
$appID = $block->getAppID();

if ($block->getPaymentMethod() === 'openpix_pix'): ?>
    <button type="button" class="action primary btn-openpix-pix" data-trigger="trigger">
        <span data-bind="i18n: '<?= $paymentInfo['text'] ?>'"></span>
    </button>
    <div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'modalClass': 'modalpix',
            'title': 'Escaneie o QRcode',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
        }}">
        <div id="openpix-order" data-appid="<?= $appID ?>" data-correlationID="<?= $correlationID ?>"></div>
        <script src="<?= $src ?>" async src_type="url"></script>
    </div>
<?php endif; ?>
