<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php
$order = $block->getOrder();
//$qrcodepix = $order->getPaghiperPix();
//$chavepix = $order->getPaghiperChavepix();
$payment = $order->getPayment();
?>
<?php if ($payment->getMethod() === 'openpix_pix') : ?>
    <div class="actions-toolbar flex">
<!--        <div class="primary">-->
<!--            <img src="--><?//= $qrcodepix ?><!--" />-->
<!--        </div>-->
        <div class="linhes">
            <h3>Linha digitável:</h3>
<!--            <textarea readonly rows="5" name="pixer" id="select-this">--><?//= $chavepix ?><!--</textarea>-->
            <div class="actions-toolbar">
                <div class="primary">
                    <button id='clickMe'>Copiar</button>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
