<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Checkout\Block\Onepage\Success */
?>
<?php
$order = $block->getOrder();
$payment = $order->getPayment();
$src = $block->getPluginSrc();
$correlationID = $block->getCorrelationID();
$appID = $block->getAppID();
?>
<?php if ($payment->getMethod() === 'openpix_pix') : ?>
    <div class="actions-toolbar flex">
        <div id="openpix-order" data-appid="<?= $block->escapeHtmlAttr($appID) ?>" data-correlationID="<?= $block->escapeHtmlAttr($correlationID) ?>"></div>

        <script>
            require(["jquery", "OpenPix"], function($, pym) {});
        </script>
    </div>
<?php elseif ($payment->getMethod() === 'openpix_pix_parcelado') : ?>
    <div class="actions-toolbar flex">
        <div id="openpix-order" data-appid="<?= $block->escapeHtmlAttr($appID) ?>" data-correlationID="<?= $block->escapeHtmlAttr($correlationID) ?>"></div>

        <script>
            require(["jquery", "OpenPix"], function($, pym) {});
        </script>
    </div>
<?php endif; ?>