<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \OpenPix\Pix\Block\Checkout\Success */
?>
<?php
$order = $block->getOrder();
$payment = $order->getPayment();
$src = $block->getPluginSrc();
?>
<?php if ($payment->getMethod() === 'openpix_pix'): ?>
    <script policy id="script-src" src="<?= $src ?>" async></script>
    <div id='openpix-order' style='margin-bottom: 40px'></div>

<?php endif; ?>
