<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage\Success */

$src = $block->getPluginSrc();
$qrCodes = $block->getQrCodes();
$correlationID = $block->getCorrelationID();
$appID = $block->getAppID();
?>

<?php foreach ($qrCodes as $qrCode): ?>
    <div class="actions-toolbar flex">
        <div id="openpix-order" data-appid="<?= $block->escapeHtmlAttr($appID) ?>" data-correlationID="<?= $block->escapeHtmlAttr($qrCode['correlationID']) ?>"></div>

        <script>
            require(["jquery", "OpenPix"], function($, pym) {});
        </script>
    </div>
<?php endforeach; ?>