<?php /* @var $block \OpenPix\Pix\Block\System\Config\Button */ ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        $('payment_us_openpix_configurations_openpix_credentials_webhook_authorization').setAttribute('readonly','true')
        $('payment_us_openpix_configurations_openpix_credentials_webhook_hmac_authorization').setAttribute('readonly','true')
        $('payment_us_openpix_configurations_openpix_credentials_webhook_status').setAttribute('readonly','true')
        jQuery('#openpix_webhook_button').click(function () {
            var params = {
                app_ID: $('payment_us_openpix_configurations_openpix_credentials_app_ID').value
            };

            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                loaderArea:     false,
                asynchronous:   true,
                parameters:     params,
                onComplete: function(transport) {
                    if (transport.responseText.isJSON()) {
                        var response = transport.responseText.evalJSON();
                        console.log(response);
                        if(response?.success) {
                            if(response?.body?.webhook_authorization) {
                                jQuery("#payment_us_openpix_configurations_openpix_credentials_webhook_authorization").val(response.body.webhook_authorization);
                            }
                            if(response?.body?.hmac_authorization) {
                                jQuery("#payment_us_openpix_configurations_openpix_credentials_webhook_hmac_authorization").val(response.body.hmac_authorization);
                            }
                            if(response?.body?.webhook_status) {
                                jQuery("#payment_us_openpix_configurations_openpix_credentials_webhook_status").val(response.body.webhook_status);
                            }
                        }
                        if(response?.message) {
                            alert(response.message);
                        }
                    }
                }
            });
        });
    });
</script>
<?php echo $block->getButtonHtml(); ?>
<p>
    <span id="custom_button_response_message"></span>
</p>
